services:
  dev:
    image: ghcr.io/tom-molloy/modular-laravel/vite-dev:${TAG:-local}
    build:
      context: .
      target: vite-dev
    depends_on:
      - php-fpm
    ports:
      - '5173:5173'
    volumes:
      - .:/example-app

  php-fpm:
    image: ghcr.io/tom-molloy/modular-laravel/php-fpm-dev:${TAG:-local}
    build:
      context: .
      target: php-fpm-dev
    depends_on:
      - postgres
    ports:
      - '8000:8000'
    volumes:
      - .:/var/www/html

  postgres:
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGPASSWORD: password
      POSTGRES_DB: laravel
    networks:
      default:
        aliases:
          - postgres.local
    volumes:
      - db:/var/lib/postgresql/data

  composer:
    image: ghcr.io/tom-molloy/modular-laravel/php-fpm-dev:${TAG:-local}
    user: '1000:1000'
    volumes:
      - .:/var/www/html
    entrypoint: composer

  artisan:
    image: ghcr.io/tom-molloy/modular-laravel/php-fpm-dev:${TAG:-local}
    depends_on:
      - postgres
    user: '1000:1000'
    volumes:
      - .:/var/www/html
    entrypoint: php artisan

  npm:
    image: ghcr.io/tom-molloy/modular-laravel/php-fpm-dev:${TAG:-local}
    volumes:
      - .:/example-app
    entrypoint: npm

  test:
    image: ghcr.io/tom-molloy/modular-laravel/php-fpm-dev:${TAG:-local}
    environment:
      APP_ENV: testing # use .env.testing
    depends_on:
      - postgres
    user: '1000:1000'
    entrypoint: php artisan test

  psql:
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGPASSWORD: password
      POSTGRES_DB: example_app
    entrypoint: psql -h postgres.local -Uuser example_app

volumes:
  db: