services:
  dev:
    extends:
      file: compose.base.yml
      service: dev
    volumes:
      - .:/example-app

  php-fpm:
    extends:
      file: compose.base.yml
      service: php-fpm
    volumes:
      - .:/var/www/html

  postgres:
    extends:
      file: compose.base.yml
      service: postgres
    volumes:
      - ./bin/init-testing-db.sh:/docker-entrypoint-initdb.d/init-testing-db.sh
      - db:/var/lib/postgresql/data

  composer:
    extends:
      file: compose.base.yml
      service: composer
    volumes:
      - .:/var/www/html

  artisan:
    extends:
      file: compose.base.yml
      service: artisan
    volumes:
      - .:/var/www/html

  npm:
    extends:
      file: compose.base.yml
      service: npm
    volumes:
      - .:/example-app

volumes:
  db: